# Use custom format
format = '''
$directory$git_branch$git_commit$git_status$git_state$fill$container$python$nix_shell$cmd_duration
$character'''

continuation_prompt = '$character'

# Disable the blank line at the start of the prompt
add_newline = true

# Set 'rose-pine' as custom color palette
palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[character]
success_symbol = '[❯](bold fg:pine)'
error_symbol = '[❯](bold fg:love)'

[directory]
truncation_length = 8
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold fg:foam'
# to show full path on git repos
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
symbol = ""
style = "fg:iris"

[git_commit]
style = "fg:iris"

[git_state]
style = "fg:love"

[git_status]
format = ' ([$all_status$ahead_behind]($style) )'
conflicted = '='
ahead = '⇡$count '
behind = '⇣$count '
diverged = '⇕ ⇡$ahead_count ⇣$behind_count '
untracked = '?$count '
stashed = '$$count '
modified = '!$count '
staged = '+$count '
renamed = '>$count '
deleted = 'x$count '
style = 'fg:gold'

[fill]
symbol = ' '

[container]
format = '[/($name/)]($style) '
style = 'fg:rose'

[python]
format = '[\($virtualenv\)]($style) '
style = 'fg:rose'

[nix_shell]
impure_msg = '[impure](fg:love)'
pure_msg = '[pure](fg:foam)'
unknown_msg = '[unknown](fg:gold)'
format = '[$state( \($name\))](fg:rose) '

[cmd_duration]
min_time = 2000
format = '[$duration](fg:gold)'
